CREATE TABLE IF NOT EXISTS Ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Összetevő_neve VARCHAR(255),
    Mennyiség INTEGER,
    Mértékegység VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Vendégek (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Név VARCHAR(255),
    Telefon VARCHAR(255),
    Email VARCHAR(255),
    Cím VARCHAR(255),
    Megjegyzés VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Megrendelések (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    Megrendelés_dátuma DATE,
    Megrendelés_időpontja TIME,
    darab VARCHAR(255),
    "teljes ár" INTEGER
);

CREATE TABLE IF NOT EXISTS Bowl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tál_típusa VARCHAR(255),
    order_id BIGINT,
    Mennyiség INTEGER,
    Mértékegység VARCHAR(255),
    Ár INTEGER
);

CREATE TABLE IF NOT EXISTS bowl_ingredients (
    bowl_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL
);

INSERT INTO Ingredient (Összetevő_neve, Mennyiség, Mértékegység)
SELECT 'Csirkemell', 5, 'KG'
WHERE NOT EXISTS (
    SELECT 1 FROM Ingredient WHERE Összetevő_neve = 'Csirkemell'
);

INSERT INTO Ingredient (Összetevő_neve, Mennyiség, Mértékegység)
SELECT 'Jazmin rizs', 3, 'KG'
WHERE NOT EXISTS (
    SELECT 1 FROM Ingredient WHERE Összetevő_neve = 'Jazmin rizs'
);

INSERT INTO Ingredient (Összetevő_neve, Mennyiség, Mértékegység)
SELECT 'Uborka', 2, 'KG'
WHERE NOT EXISTS (
    SELECT 1 FROM Ingredient WHERE Összetevő_neve = 'Uborka'
);

INSERT INTO Ingredient (Összetevő_neve, Mennyiség, Mértékegység)
SELECT 'Szezámmag', 500, 'G'
WHERE NOT EXISTS (
    SELECT 1 FROM Ingredient WHERE Összetevő_neve = 'Szezámmag'
);

INSERT INTO Ingredient (Összetevő_neve, Mennyiség, Mértékegység)
SELECT 'Teriyaki szosz', 8, 'DL'
WHERE NOT EXISTS (
    SELECT 1 FROM Ingredient WHERE Összetevő_neve = 'Teriyaki szosz'
);

INSERT INTO Vendégek (Név, Telefon, Email, Cím, Megjegyzés)
SELECT 'Kiss Anna', '+3612345678', 'anna.kiss@example.com', '1117 Budapest, Bartok Bela ut 12.', 'Online rendeles'
WHERE NOT EXISTS (
    SELECT 1 FROM Vendégek WHERE Email = 'anna.kiss@example.com'
);

INSERT INTO Vendégek (Név, Telefon, Email, Cím, Megjegyzés)
SELECT 'Nagy Peter', '+36201234567', 'peter.nagy@example.com', '1024 Budapest, Feny utca 7.', 'Torzsvendeg'
WHERE NOT EXISTS (
    SELECT 1 FROM Vendégek WHERE Email = 'peter.nagy@example.com'
);

INSERT INTO Megrendelések (customer_id, Megrendelés_dátuma, Megrendelés_időpontja, darab, "teljes ár")
SELECT
    (SELECT id FROM Vendégek WHERE Email = 'anna.kiss@example.com'),
    DATE '2026-03-01',
    TIME '11:30:00',
    '1',
    2890
WHERE NOT EXISTS (
    SELECT 1
    FROM Megrendelések
    WHERE customer_id = (SELECT id FROM Vendégek WHERE Email = 'anna.kiss@example.com')
      AND Megrendelés_dátuma = DATE '2026-03-01'
      AND Megrendelés_időpontja = TIME '11:30:00'
);

INSERT INTO Megrendelések (customer_id, Megrendelés_dátuma, Megrendelés_időpontja, darab, "teljes ár")
SELECT
    (SELECT id FROM Vendégek WHERE Email = 'peter.nagy@example.com'),
    DATE '2026-03-02',
    TIME '12:15:00',
    '1',
    3290
WHERE NOT EXISTS (
    SELECT 1
    FROM Megrendelések
    WHERE customer_id = (SELECT id FROM Vendégek WHERE Email = 'peter.nagy@example.com')
      AND Megrendelés_dátuma = DATE '2026-03-02'
      AND Megrendelés_időpontja = TIME '12:15:00'
);

INSERT INTO Megrendelések (customer_id, Megrendelés_dátuma, Megrendelés_időpontja, darab, "teljes ár")
SELECT
    (SELECT id FROM Vendégek WHERE Email = 'anna.kiss@example.com'),
    DATE '2026-03-03',
    TIME '18:05:00',
    '1',
    2690
WHERE NOT EXISTS (
    SELECT 1
    FROM Megrendelések
    WHERE customer_id = (SELECT id FROM Vendégek WHERE Email = 'anna.kiss@example.com')
      AND Megrendelés_dátuma = DATE '2026-03-03'
      AND Megrendelés_időpontja = TIME '18:05:00'
);

INSERT INTO Bowl (Tál_típusa, order_id, Mennyiség, Mértékegység, Ár)
SELECT
    'Csipos csirke bowl',
    (
        SELECT id
        FROM Megrendelések
        WHERE customer_id = (SELECT id FROM Vendégek WHERE Email = 'anna.kiss@example.com')
          AND Megrendelés_dátuma = DATE '2026-03-01'
          AND Megrendelés_időpontja = TIME '11:30:00'
    ),
    1,
    'db',
    2890
WHERE NOT EXISTS (
    SELECT 1 FROM Bowl WHERE Tál_típusa = 'Csipos csirke bowl'
);

INSERT INTO Bowl (Tál_típusa, order_id, Mennyiség, Mértékegység, Ár)
SELECT
    'Teriyaki lazac bowl',
    (
        SELECT id
        FROM Megrendelések
        WHERE customer_id = (SELECT id FROM Vendégek WHERE Email = 'peter.nagy@example.com')
          AND Megrendelés_dátuma = DATE '2026-03-02'
          AND Megrendelés_időpontja = TIME '12:15:00'
    ),
    1,
    'db',
    3290
WHERE NOT EXISTS (
    SELECT 1 FROM Bowl WHERE Tál_típusa = 'Teriyaki lazac bowl'
);

INSERT INTO Bowl (Tál_típusa, order_id, Mennyiség, Mértékegység, Ár)
SELECT
    'Tofu power bowl',
    (
        SELECT id
        FROM Megrendelések
        WHERE customer_id = (SELECT id FROM Vendégek WHERE Email = 'anna.kiss@example.com')
          AND Megrendelés_dátuma = DATE '2026-03-03'
          AND Megrendelés_időpontja = TIME '18:05:00'
    ),
    1,
    'db',
    2690
WHERE NOT EXISTS (
    SELECT 1 FROM Bowl WHERE Tál_típusa = 'Tofu power bowl'
);

INSERT INTO Bowl (Tál_típusa, Mennyiség, Mértékegység, Ár)
SELECT 'Zoldseg mix bowl', 1, 'db', 2490
WHERE NOT EXISTS (
    SELECT 1 FROM Bowl WHERE Tál_típusa = 'Zoldseg mix bowl'
);

INSERT INTO Bowl (Tál_típusa, Mennyiség, Mértékegység, Ár)
SELECT 'Marha steak bowl', 1, 'db', 3590
WHERE NOT EXISTS (
    SELECT 1 FROM Bowl WHERE Tál_típusa = 'Marha steak bowl'
);

INSERT INTO bowl_ingredients (bowl_id, ingredient_id)
SELECT
    (SELECT id FROM Bowl WHERE Tál_típusa = 'Csipos csirke bowl'),
    (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Csirkemell')
WHERE NOT EXISTS (
    SELECT 1
    FROM bowl_ingredients
    WHERE bowl_id = (SELECT id FROM Bowl WHERE Tál_típusa = 'Csipos csirke bowl')
      AND ingredient_id = (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Csirkemell')
);

INSERT INTO bowl_ingredients (bowl_id, ingredient_id)
SELECT
    (SELECT id FROM Bowl WHERE Tál_típusa = 'Csipos csirke bowl'),
    (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Jazmin rizs')
WHERE NOT EXISTS (
    SELECT 1
    FROM bowl_ingredients
    WHERE bowl_id = (SELECT id FROM Bowl WHERE Tál_típusa = 'Csipos csirke bowl')
      AND ingredient_id = (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Jazmin rizs')
);

INSERT INTO bowl_ingredients (bowl_id, ingredient_id)
SELECT
    (SELECT id FROM Bowl WHERE Tál_típusa = 'Teriyaki lazac bowl'),
    (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Teriyaki szosz')
WHERE NOT EXISTS (
    SELECT 1
    FROM bowl_ingredients
    WHERE bowl_id = (SELECT id FROM Bowl WHERE Tál_típusa = 'Teriyaki lazac bowl')
      AND ingredient_id = (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Teriyaki szosz')
);

INSERT INTO bowl_ingredients (bowl_id, ingredient_id)
SELECT
    (SELECT id FROM Bowl WHERE Tál_típusa = 'Zoldseg mix bowl'),
    (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Uborka')
WHERE NOT EXISTS (
    SELECT 1
    FROM bowl_ingredients
    WHERE bowl_id = (SELECT id FROM Bowl WHERE Tál_típusa = 'Zoldseg mix bowl')
      AND ingredient_id = (SELECT id FROM Ingredient WHERE Összetevő_neve = 'Uborka')
);
